name: Build And Push Docker Image

on:
  push:
    branches:
      - 'my-develop'
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  watch:
    types: [started]

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate App Version
        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          build-args: |
            MAINTAINER=${{ github.repository_owner }}
            QL_BRANCH=${{ github.ref_name }}
            SOURCE_COMMIT=${{ github.sha }}
          network: host
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x,linux/386
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ env.APP_VERSION }}
          cache-from: type=registry,ref=${{ github.repository }}:cache
          cache-to: type=registry,ref=${{ github.repository }}:cache,mode=max

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
